Homework
thetrace666/lesson5 pull request #2
Opened 2021-05-31 00:12 UTC by thetrace666

2021-05-31 14:00 UTC, dbradultest requested changes

2021-05-31 14:00 UTC, dbradultest commented on db.py
> +            f'WHERE genres.name = "{args["genre"]}" GROUP by customers.City ORDER by COUNT(customers.City) DESC '
Здесь вы считаете кол-во продаж, а правильнее, наверное, кол-во проданных треков (`sum(invoice_items.quantity)`).
И обычно агрегирующие функции размещают в SELECT'e. Если вы все-равно считате информацию, то как правило интересно по не только сортироваться, но и отображать.

2021-05-31 20:50 UTC, thetrace666 commented on db.py
> +            'ORDER by invoice_items.quantity DESC '
В задание указано вывести count самых продаваемых треков. Если я буду сортировать по сумме продажи может получиться ситуация где  5 копий по 10 гривен встанут ниже чем 1 копия за 100 гривен.

2021-05-31 21:08 UTC, thetrace666 commented on db.py
> +            f'WHERE genres.name = "{args["genre"]}" GROUP by customers.City ORDER by COUNT(customers.City) DESC '
Это одинаковые значения COUNT(customers.City) = sum(invoice_items.quantity)

2021-05-31 21:27 UTC, thetrace666 commented on .idea/workspace.xml
> +</project>
уже исправил до того момента как вы написали

2021-06-01 09:15 UTC, dbradultest approved these changes
LGTM

2021-06-01 09:15 UTC, dbradultest commented on db.py
> +            'ORDER by invoice_items.quantity DESC '
Да, вы правы по поводу количества.
При одинаковом кол-ве, можно дополнителньо сортировать по сумме продаж.
```
SELECT ... sum(invoice_items.quantity *  invoice_items.UnitPrice) as total_sum
...
ORDER BY invoice_items.Quantity DESC, total_sum DESC
```

2021-06-01 11:57 UTC, merged